-- File generated by the BNF Converter (bnfc 2.9.6.3).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}

-- | Pretty-printer for QurtsGrammar.

module QurtsGrammar.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified QurtsGrammar.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print QurtsGrammar.Abs.Ident where
  prt _ (QurtsGrammar.Abs.Ident i) = doc $ showString i
instance Print [QurtsGrammar.Abs.Function] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ";"), prt 0 xs]

instance Print [QurtsGrammar.Abs.Param] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [QurtsGrammar.Abs.Lifetime] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [QurtsGrammar.Abs.Ident] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print [QurtsGrammar.Abs.LifetimeConstraint] where
  prt _ [] = concatD []
  prt _ [x] = concatD [prt 0 x]
  prt _ (x:xs) = concatD [prt 0 x, doc (showString ","), prt 0 xs]

instance Print QurtsGrammar.Abs.Program where
  prt i = \case
    QurtsGrammar.Abs.Program functions -> prPrec i 0 (concatD [prt 0 functions])

instance Print QurtsGrammar.Abs.Function where
  prt i = \case
    QurtsGrammar.Abs.Function id_ signature block -> prPrec i 0 (concatD [doc (showString "fn"), prt 0 id_, prt 0 signature, prt 0 block])

instance Print QurtsGrammar.Abs.Signature where
  prt i = \case
    QurtsGrammar.Abs.Signature lifetimecontext params type_ -> prPrec i 0 (concatD [prt 0 lifetimecontext, doc (showString "("), prt 0 params, doc (showString ")"), doc (showString "->"), prt 0 type_])

instance Print QurtsGrammar.Abs.Param where
  prt i = \case
    QurtsGrammar.Abs.Param id_ type_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString ":"), prt 0 type_])

instance Print QurtsGrammar.Abs.LifetimeContext where
  prt i = \case
    QurtsGrammar.Abs.LifetimeContext lifetimes lifetimeconstraints -> prPrec i 0 (concatD [doc (showString "<"), prt 0 lifetimes, doc (showString "|"), prt 0 lifetimeconstraints, doc (showString ">")])

instance Print QurtsGrammar.Abs.LifetimeConstraint where
  prt i = \case
    QurtsGrammar.Abs.LifetimeConstraint lifetime1 lifetime2 -> prPrec i 0 (concatD [prt 0 lifetime1, doc (showString "<="), prt 0 lifetime2])

instance Print QurtsGrammar.Abs.Block where
  prt i = \case
    QurtsGrammar.Abs.Block stmt id_ -> prPrec i 0 (concatD [doc (showString "{"), prt 0 stmt, doc (showString ";"), prt 0 id_, doc (showString "}")])

instance Print QurtsGrammar.Abs.Stmt where
  prt i = \case
    QurtsGrammar.Abs.Stmt simplestmt -> prPrec i 0 (concatD [prt 0 simplestmt])
    QurtsGrammar.Abs.StmtSeq stmt simplestmt -> prPrec i 0 (concatD [prt 0 stmt, doc (showString ";"), prt 0 simplestmt])

instance Print QurtsGrammar.Abs.SimpleStmt where
  prt i = \case
    QurtsGrammar.Abs.SimpleStmtNoop -> prPrec i 0 (concatD [doc (showString "noop")])
    QurtsGrammar.Abs.SimpleStmtNewLft lifetime -> prPrec i 0 (concatD [doc (showString "newlft"), prt 0 lifetime])
    QurtsGrammar.Abs.SimpleStmtEndLft lifetime -> prPrec i 0 (concatD [doc (showString "endlft"), prt 0 lifetime])
    QurtsGrammar.Abs.SimpleStmtLeq lifetime1 lifetime2 -> prPrec i 0 (concatD [prt 0 lifetime1, doc (showString "<="), prt 0 lifetime2])
    QurtsGrammar.Abs.SimpleStmtAs id_ type_ -> prPrec i 0 (concatD [prt 0 id_, doc (showString "as"), prt 0 type_])
    QurtsGrammar.Abs.SimpleStmtLetRef id_1 lifetime id_2 -> prPrec i 0 (concatD [doc (showString "let"), prt 0 id_1, doc (showString "="), doc (showString "&"), prt 0 lifetime, prt 0 id_2])
    QurtsGrammar.Abs.SimpleStmtLetExpr id_ expr -> prPrec i 0 (concatD [doc (showString "let"), prt 0 id_, doc (showString "="), prt 0 expr])
    QurtsGrammar.Abs.SimpleStmtLetPair id_1 id_2 id_3 -> prPrec i 0 (concatD [doc (showString "let"), doc (showString "("), prt 0 id_1, doc (showString ","), prt 0 id_2, doc (showString ")"), doc (showString "="), prt 0 id_3])
    QurtsGrammar.Abs.SimpleStmtDrop id_ -> prPrec i 0 (concatD [doc (showString "drop"), prt 0 id_])

instance Print QurtsGrammar.Abs.Expr where
  prt i = \case
    QurtsGrammar.Abs.EVar id_ -> prPrec i 0 (concatD [prt 0 id_])
    QurtsGrammar.Abs.ETrue -> prPrec i 0 (concatD [doc (showString "true")])
    QurtsGrammar.Abs.EFalse -> prPrec i 0 (concatD [doc (showString "false")])
    QurtsGrammar.Abs.EUnit -> prPrec i 0 (concatD [doc (showString "("), doc (showString ")")])
    QurtsGrammar.Abs.EPair id_1 id_2 -> prPrec i 0 (concatD [doc (showString "("), prt 0 id_1, doc (showString ","), prt 0 id_2, doc (showString ")")])
    QurtsGrammar.Abs.ECopy id_ -> prPrec i 0 (concatD [doc (showString "copy"), prt 0 id_])
    QurtsGrammar.Abs.EMeas id_ -> prPrec i 0 (concatD [doc (showString "meas"), doc (showString "("), prt 0 id_, doc (showString ")")])
    QurtsGrammar.Abs.EU id_1 id_2 -> prPrec i 0 (concatD [prt 0 id_1, doc (showString "("), prt 0 id_2, doc (showString ")")])
    QurtsGrammar.Abs.EC id_1 id_2 -> prPrec i 0 (concatD [doc (showString "["), prt 0 id_1, doc (showString "]"), doc (showString "("), prt 0 id_2, doc (showString ")")])
    QurtsGrammar.Abs.EInit0 -> prPrec i 0 (concatD [doc (showString "["), doc (showString "0"), doc (showString "]"), doc (showString "("), doc (showString ")")])
    QurtsGrammar.Abs.EInit1 -> prPrec i 0 (concatD [doc (showString "["), doc (showString "1"), doc (showString "]"), doc (showString "("), doc (showString ")")])
    QurtsGrammar.Abs.ECall id_ lifetimes ids -> prPrec i 0 (concatD [prt 0 id_, doc (showString "<"), prt 0 lifetimes, doc (showString ">"), doc (showString "("), prt 0 ids, doc (showString ")")])
    QurtsGrammar.Abs.EIf id_ block1 block2 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 id_, prt 0 block1, doc (showString "else"), prt 0 block2])
    QurtsGrammar.Abs.EQIf id_ block1 block2 -> prPrec i 0 (concatD [doc (showString "qif"), prt 0 id_, prt 0 block1, doc (showString "else"), prt 0 block2])

instance Print QurtsGrammar.Abs.Type where
  prt i = \case
    QurtsGrammar.Abs.TypeMul type_ prefixtype -> prPrec i 0 (concatD [prt 0 type_, doc (showString "*"), prt 0 prefixtype])
    QurtsGrammar.Abs.TypePrefix prefixtype -> prPrec i 0 (concatD [prt 0 prefixtype])

instance Print QurtsGrammar.Abs.PrefixType where
  prt i = \case
    QurtsGrammar.Abs.TypePrefixRef lifetime prefixtype -> prPrec i 0 (concatD [doc (showString "&"), prt 0 lifetime, prt 0 prefixtype])
    QurtsGrammar.Abs.TypePrefixBang lifetime prefixtype -> prPrec i 0 (concatD [doc (showString "#"), prt 0 lifetime, prt 0 prefixtype])
    QurtsGrammar.Abs.TypeAtomBool -> prPrec i 0 (concatD [doc (showString "bool")])
    QurtsGrammar.Abs.TypeAtomQbit -> prPrec i 0 (concatD [doc (showString "qbit")])
    QurtsGrammar.Abs.TypeAtomUnit -> prPrec i 0 (concatD [doc (showString "("), doc (showString ")")])

instance Print QurtsGrammar.Abs.Lifetime where
  prt i = \case
    QurtsGrammar.Abs.LVar id_ -> prPrec i 0 (concatD [prt 0 id_])
    QurtsGrammar.Abs.LBottom -> prPrec i 0 (concatD [doc (showString "bot")])
    QurtsGrammar.Abs.LTop -> prPrec i 0 (concatD [doc (showString "top")])
