-- File generated by the BNF Converter (bnfc 2.9.6.3).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -Wno-unused-matches #-}

module QurtsGrammar.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified QurtsGrammar.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transIdent :: QurtsGrammar.Abs.Ident -> Result
transIdent x = case x of
  QurtsGrammar.Abs.Ident string -> failure x

transProgram :: QurtsGrammar.Abs.Program -> Result
transProgram x = case x of
  QurtsGrammar.Abs.Program functions -> failure x

transFunction :: QurtsGrammar.Abs.Function -> Result
transFunction x = case x of
  QurtsGrammar.Abs.Function ident signature block -> failure x

transSignature :: QurtsGrammar.Abs.Signature -> Result
transSignature x = case x of
  QurtsGrammar.Abs.Signature lifetimecontext params type_ -> failure x

transParam :: QurtsGrammar.Abs.Param -> Result
transParam x = case x of
  QurtsGrammar.Abs.Param ident type_ -> failure x

transLifetimeContext :: QurtsGrammar.Abs.LifetimeContext -> Result
transLifetimeContext x = case x of
  QurtsGrammar.Abs.LifetimeContext lifetimes lifetimeconstraints -> failure x

transLifetimeConstraint :: QurtsGrammar.Abs.LifetimeConstraint -> Result
transLifetimeConstraint x = case x of
  QurtsGrammar.Abs.LifetimeConstraint lifetime1 lifetime2 -> failure x

transBlock :: QurtsGrammar.Abs.Block -> Result
transBlock x = case x of
  QurtsGrammar.Abs.Block stmt ident -> failure x

transStmt :: QurtsGrammar.Abs.Stmt -> Result
transStmt x = case x of
  QurtsGrammar.Abs.Stmt simplestmt -> failure x
  QurtsGrammar.Abs.StmtSeq stmt simplestmt -> failure x

transSimpleStmt :: QurtsGrammar.Abs.SimpleStmt -> Result
transSimpleStmt x = case x of
  QurtsGrammar.Abs.SimpleStmtNoop -> failure x
  QurtsGrammar.Abs.SimpleStmtNewLft lifetime -> failure x
  QurtsGrammar.Abs.SimpleStmtEndLft lifetime -> failure x
  QurtsGrammar.Abs.SimpleStmtLeq lifetime1 lifetime2 -> failure x
  QurtsGrammar.Abs.SimpleStmtAs ident type_ -> failure x
  QurtsGrammar.Abs.SimpleStmtLetRef ident1 lifetime ident2 -> failure x
  QurtsGrammar.Abs.SimpleStmtLetExpr ident expr -> failure x
  QurtsGrammar.Abs.SimpleStmtLetPair ident1 ident2 ident3 -> failure x
  QurtsGrammar.Abs.SimpleStmtDrop ident -> failure x

transExpr :: QurtsGrammar.Abs.Expr -> Result
transExpr x = case x of
  QurtsGrammar.Abs.EVar ident -> failure x
  QurtsGrammar.Abs.ETrue -> failure x
  QurtsGrammar.Abs.EFalse -> failure x
  QurtsGrammar.Abs.EUnit -> failure x
  QurtsGrammar.Abs.EPair ident1 ident2 -> failure x
  QurtsGrammar.Abs.ECopy ident -> failure x
  QurtsGrammar.Abs.EMeas ident -> failure x
  QurtsGrammar.Abs.EU ident1 ident2 -> failure x
  QurtsGrammar.Abs.EC ident1 ident2 -> failure x
  QurtsGrammar.Abs.EInit0 -> failure x
  QurtsGrammar.Abs.EInit1 -> failure x
  QurtsGrammar.Abs.ECall ident lifetimes idents -> failure x
  QurtsGrammar.Abs.EIf ident block1 block2 -> failure x
  QurtsGrammar.Abs.EQIf ident block1 block2 -> failure x

transType :: QurtsGrammar.Abs.Type -> Result
transType x = case x of
  QurtsGrammar.Abs.TypeMul type_ prefixtype -> failure x
  QurtsGrammar.Abs.TypePrefix prefixtype -> failure x

transPrefixType :: QurtsGrammar.Abs.PrefixType -> Result
transPrefixType x = case x of
  QurtsGrammar.Abs.TypePrefixRef lifetime prefixtype -> failure x
  QurtsGrammar.Abs.TypePrefixBang lifetime prefixtype -> failure x
  QurtsGrammar.Abs.TypeAtomBool -> failure x
  QurtsGrammar.Abs.TypeAtomQbit -> failure x
  QurtsGrammar.Abs.TypeAtomUnit -> failure x

transLifetime :: QurtsGrammar.Abs.Lifetime -> Result
transLifetime x = case x of
  QurtsGrammar.Abs.LVar ident -> failure x
  QurtsGrammar.Abs.LBottom -> failure x
  QurtsGrammar.Abs.LTop -> failure x
